name: Deploy Voll Med

on:
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configura o Docker Compose
      run: |
        sudo rm -f /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build da imagem Docker
      run: docker build -t vollmed-api_api .

    - name: Roda Docker Compose
      run: docker-compose up -d

    - name: Deploy para EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        USER: ubuntu
        HOST: 107.23.247.197
      run: |
        echo "$PRIVATE_KEY" > key-vollmed-deploy.pem
        chmod 600 key-vollmed-deploy.pem

        # Salva a imagem Docker localmente
        docker save -o vollmed-api.tar vollmed-api_api

        # Envia os arquivos para o EC2
        scp -o StrictHostKeyChecking=no -i key-vollmed-deploy.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i key-vollmed-deploy.pem init.sql $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i key-vollmed-deploy.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i key-vollmed-deploy.pem script-deploy.sh $USER@$HOST:/home/ubuntu/        

        # Acessa o EC2 e executa o script de deploy
        ssh -i key-vollmed-deploy.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh" 
